### ISSUE TITLE
[Meta] Enable windows 11 context menu by default in Stable

### ISSUE THREAD

**Issue by vscodenpa** [vscodenpa/testissues#38921]
Bug tracks the pending tasks to be completed before the feature can be promoted to stable releases.

- [ ] :hand: Context menu not appearing on some setups even after successful appx installation (https://github-com/microsoft/vscode/-/184676, https://github-com/microsoft/vscode/-/171911)
- [ ] :runner: Uninstallation takes longer time when context menu is installed (https://github-com/microsoft/vscode/-/164689)
- [ ] :runner: Context menu not showing up in Windows Arm64 (https://github-com/microsoft/vscode/-/164464)
- [ ] Run as administrator does not trigger UAC elevation prompt when launching application from context menu (https://github-com/microsoft/vscode/-/180065)
